package com.mpin;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/** Builds the Excel file in memory from this session's MPINs — no file on disk needed. */
@WebServlet("/downloadExcel")
public class DownloadExcelServlet extends HttpServlet {

    private static final String[] HEADERS = {"#", "Label / Purpose", "MPIN", "Length", "Generated At", "Generated By"};
    private static final DateTimeFormatter DISPLAY = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm:ss");
    private static final DateTimeFormatter FILE = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        List<MpinRecord> records = MpinHistory.snapshot(req.getSession(false));

        try (XSSFWorkbook wb = new XSSFWorkbook()) {
            Sheet sheet = wb.createSheet("MPINs");

            CellStyle header = wb.createCellStyle();
            Font bold = wb.createFont();
            bold.setBold(true);
            bold.setColor(IndexedColors.WHITE.getIndex());
            header.setFont(bold);
            header.setFillForegroundColor(IndexedColors.DARK_TEAL.getIndex());
            header.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            header.setAlignment(HorizontalAlignment.CENTER);
            header.setBorderBottom(BorderStyle.THIN);

            // MPINs are stored as text so leading zeros (e.g. 0471) survive.
            CellStyle text = wb.createCellStyle();
            text.setDataFormat(wb.createDataFormat().getFormat("@"));
            text.setAlignment(HorizontalAlignment.CENTER);

            CellStyle center = wb.createCellStyle();
            center.setAlignment(HorizontalAlignment.CENTER);

            Row head = sheet.createRow(0);
            for (int i = 0; i < HEADERS.length; i++) {
                Cell cell = head.createCell(i);
                cell.setCellValue(HEADERS[i]);
                cell.setCellStyle(header);
            }

            int rowIndex = 1;
            for (MpinRecord r : records) {
                Row row = sheet.createRow(rowIndex);
                row.createCell(0).setCellValue(rowIndex);
                row.getCell(0).setCellStyle(center);
                row.createCell(1).setCellValue(r.label());
                Cell pin = row.createCell(2);
                pin.setCellValue(r.mpin());
                pin.setCellStyle(text);
                row.createCell(3).setCellValue(r.length() + " digit");
                row.getCell(3).setCellStyle(center);
                row.createCell(4).setCellValue(DISPLAY.format(r.generatedAt()));
                row.createCell(5).setCellValue(r.generatedBy());
                rowIndex++;
            }

            sheet.createFreezePane(0, 1);
            int[] widths = {6, 32, 12, 10, 24, 18};
            for (int i = 0; i < widths.length; i++) {
                sheet.setColumnWidth(i, widths[i] * 256);
            }

            resp.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            resp.setHeader("Content-Disposition",
                    "attachment; filename=\"mpin_data_" + FILE.format(LocalDateTime.now()) + ".xlsx\"");
            wb.write(resp.getOutputStream());
        }
    }
}
